package com.olivias.panaderia.controller;

import com.olivias.panaderia.dto.ProductoDTO;
import com.olivias.panaderia.model.Producto;
import com.olivias.panaderia.service.ProductoService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController 
@RequestMapping("/api/productos")
public class ProductoController {

    @Autowired 
    private ProductoService productoService;

    @GetMapping
    public List<Producto> listarProductos() {
        return productoService.obtenerTodos();
    }

    @PostMapping
    public ResponseEntity<Producto> crearProducto(@RequestBody ProductoDTO productoDTO) {
        Producto nuevoProducto = new Producto();
        nuevoProducto.setNombre(productoDTO.getNombre());
        nuevoProducto.setDescripcion(productoDTO.getDescripcion());
        nuevoProducto.setPrecio(productoDTO.getPrecio());
        nuevoProducto.setCategoriaSalud(productoDTO.getCategoriaSalud());

     
        Producto guardado = productoService.guardarProducto(nuevoProducto);
      
        return new ResponseEntity<>(guardado, HttpStatus.CREATED);
    }

   
    @DeleteMapping("/{id}")
    public ResponseEntity<String> eliminarProducto(@PathVariable Long id) {
        productoService.eliminarProducto(id);
        return ResponseEntity.ok("Producto eliminado con éxito de la vitrina.");
    }
}